### ISSUE TITLE
Plugin is not able to start a ycmd server.

### ISSUE THREAD

**Issue by ghost** [sublime-ycmd/sublime-ycmd#2] opened 2018-02-21 16:12 UTC
I have my sublime-ycmd.sublime-settings file configured as mentioned below,
```sublime-settings
{
  "ycmd_root_directory": "~/Programs/ycmd",
  "ycmd_default_settings_path": "~/Programs/ycmd/ycmd/default_settings.json",
  "ycmd_force_semantic_completion": true,
  "ycmd_python_binary_path": "python",
}
```
I have configured my default_settings.json as follows,
``` JSON
{
  "filepath_completion_use_working_dir": 0,
  "auto_trigger": 1,
  "min_num_of_chars_for_completion": 1,
  "min_num_identifier_candidate_chars": 0,
  "semantic_triggers": {"c,cpp": ["re!^#include\s+\""]},
  "filetype_specific_completion_to_disable": {
  "gitcommit": 1
  },
  "seed_identifiers_with_syntax": 0,
  "collect_identifiers_from_comments_and_strings": 0,
  "collect_identifiers_from_tags_files": 0,
  "max_num_identifier_candidates": 10,
  "max_num_candidates": 50,
  "extra_conf_globlist": [],
  "global_ycm_extra_conf": "~/Programs/ycm-global-conf.py",
  "confirm_extra_conf": 0,
  "complete_in_comments": 0,
  "complete_in_strings": 1,
  "max_diagnostics_to_display": 30,
  "filetype_whitelist": {
    "*": 1
  },
  "filetype_blacklist": {
    "tagbar": 1,
    "qf": 1,
    "notes": 1,
    "markdown": 1,
    "netrw": 1,
    "unite": 1,
    "text": 1,
    "vimwiki": 1,
    "pandoc": 1,
    "infolog": 1,
    "mail": 1
  },
  "auto_start_csharp_server": 1,
  "auto_stop_csharp_server": 1,
  "use_ultisnips_completer": 1,
  "csharp_server_port": 0,
  "hmac_secret": "",
  "server_keep_logfiles": 0,
  "gocode_binary_path": "",
  "godef_binary_path": "",
  "rust_src_path": "",
  "racerd_binary_path": "",
  "python_binary_path": "python",
  "java_jdtls_use_clean_workspace": 1
}
```

I have compiled ycmd with clang-completer tag.
Whenever I goto list YCM server option in command palette it always displays empty no servers running.
All my log files are empty except the sublime-ycmd.log file which is quite verbose here's a [link](https://pastebin.com/9EpWbFLv) to it.

P.S. Please help me out.

**Comment by akshayganeshen** [comment] 2018-02-21 22:15
@lihkak It looks like the plugin is unable to determine the file type for that file, so it does not start a server for it. Please try checking the scope in the file (Tools > Developer > Show Scope Name) and ensure that it is in the enabled scope list (add to `"ycmd_language_whitelist"`).

If the scope for the file is wrong, you can also set the syntax manually with the command palette (e.g. "Set Syntax: C" for C). That should alter the scope to be `source.c`, which would allow the plugin to start servers for it.

If neither of those fixes it, please also include the scope name so I can try to reproduce.

**Comment by ghost** [comment] 2018-02-22 09:53
ok here's my updated sublime-ycmd.sublime-settings
```sublime
{
  "ycmd_root_directory": "~/Programs/ycmd",
  "ycmd_default_settings_path": "~/Programs/ycmd/ycmd/default_settings.json",
  "ycmd_force_semantic_completion": true,
  "ycmd_python_binary_path": "python",
  "ycmd_language_whitelist": [
  "source.c",
  "source.c++",
  "source.cpp",
  "source.python",
   ]
}
```
here's my scope text for a simple c++ file
```sublime
source.c++ meta.preprocessor.include.c++
```
here's my scope text for a simple c file
```sublime
source.c
```
here's my scope text for a simple python3 file
```sublime
source.python
```
Even setting the syntax manually through command palette doesn't seem to start the ycmd server.

**Comment by akshayganeshen** [comment] 2018-02-24 03:28
Apologies for the slow reply, took me a bit to reproduce it.

The issue is in the ycmd default settings file. Replace the `"semantic_triggers"` with just an empty `{}`:

```json
{
  "filepath_completion_use_working_dir": 0,
  "auto_trigger": 1,
  "min_num_of_chars_for_completion": 1,
  "min_num_identifier_candidate_chars": 0,
  "semantic_triggers": {},
  "filetype_specific_completion_to_disable": {
    "gitcommit": 1
  },
  "seed_identifiers_with_syntax": 0,
  "collect_identifiers_from_comments_and_strings": 0,
  "collect_identifiers_from_tags_files": 0,
  "max_num_identifier_candidates": 10,
  "max_num_candidates": 50,
  "extra_conf_globlist": [],
  "global_ycm_extra_conf": "~/Programs/ycm-global-conf.py",
  "confirm_extra_conf": 0,
  "complete_in_comments": 0,
  "complete_in_strings": 1,
  "max_diagnostics_to_display": 30,
  "filetype_whitelist": {
    "*": 1
  },
  "filetype_blacklist": {
    "tagbar": 1,
    "qf": 1,
    "notes": 1,
    "markdown": 1,
    "netrw": 1,
    "unite": 1,
    "text": 1,
    "vimwiki": 1,
    "pandoc": 1,
    "infolog": 1,
    "mail": 1
  },
  "auto_start_csharp_server": 1,
  "auto_stop_csharp_server": 1,
  "use_ultisnips_completer": 1,
  "csharp_server_port": 0,
  "hmac_secret": "",
  "server_keep_logfiles": 0,
  "gocode_binary_path": "",
  "godef_binary_path": "",
  "rust_src_path": "",
  "racerd_binary_path": "",
  "python_binary_path": "python",
  "java_jdtls_use_clean_workspace": 1
}
```

An invalid escape sequence causes the server to die immediately on startup, which is why it never shows up in the server list. It turns out that ycmd uses semantic completion for includes anyway, so this configuration is totally unnecessary. In your case, it doesn't matter since `"ycmd_force_semantic_completion"` is on. I'll update the docs to reflect the changes.

Please let me know if this fixes the issue!

**Comment by ghost** [comment] 2018-02-24 11:17
Fixes the issue straight away, but shows none in completer when in "get debug info" and no autocomplete suggestion seem to popup.

**Comment by akshayganeshen** [comment] 2018-02-24 21:30
Sorry, closed this without reading the full comment. I'll look into that soon too.

**Comment by akshayganeshen** [comment] 2018-02-25 05:05
I've been able to reproduce what you described by creating an error in the global `.ycm_extra_conf.py`. Try disabling that to see if that's the case. The ycmd logs had the error message and a traceback.

The server logs can be opened with "Manage server > Logs". Add these settings as well:

```json
  "ycmd_log_level": "debug",
  "ycmd_log_file": true,
```

**Comment by ghost** [comment] 2018-02-25 05:29
Completer now shows C_family but autocomplete suggestion still don't pop up now that ```.ycm_extra_conf.py ``` is disabled, but without semantic_triggers how is it supposed to work.

**Comment by akshayganeshen** [comment] 2018-02-25 05:57
Semantic triggers are used within ycmd itself to decide when it should do an expensive clang completion vs. just a quick identifier listing. Entries in `"semantic_triggers"` are added on top of built-in rules. I was able to get automatic semantic completions for `#include` with the default `"semantic_triggers": {}`.

In either case, the plugin should still be able to display a list of completions. For identifiers, all options will be labelled with `ident`. If no completions pop up at all, it's very likely that there is an error in the logs.

Since you have `"ycmd_force_semantic_completion"` enabled, it (should) force the expensive clang completion every single time. This should result in some errors in the logs (e.g. no compile flags yet). Since you also have `"confirm_extra_conf": 0`, ycmd will refuse to load `.ycm_extra_conf.py`, so that error message will appear along with every response.

Try starting with the default plugin settings (comment out everything except `"ycmd_root_directory"`) and the [default ycmd settings](https://github.com/Valloric/ycmd/blob/master/ycmd/default_settings.json). If that works, try adding in the rest of the settings until it breaks.

**Comment by ghost** [comment] 2018-02-25 06:10
Everything works now thank you very much please close the issue.

**Closed as completed** 2018-02-25 19:33 UTC
